packages:
  - packages/container/examples/*
  - packages/container/libraries/*
  - packages/container/tools/*
  - packages/docs/services/*
  - packages/docs/tools/*
  - packages/foundation/libraries/*
  - packages/foundation/tools/*
  - packages/http/libraries/*
  - packages/http/tools/*
  - packages/json-schema/libraries/*
  - packages/logger
  - packages/open-api/libraries/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
