packages:
  - packages/container/examples/*
  - packages/container/libraries/*
  - packages/container/tools/*
  - packages/docs/services/*
  - packages/docs/tools/*
  - packages/foundation/libraries/*
  - packages/foundation/tools/*
  - packages/framework/*
  - packages/framework/http/libraries/*
  - packages/framework/http/tools/*
  - packages/framework/validation/libraries/*
  - packages/json-schema/libraries/*
  - packages/logger
  - packages/open-api/libraries/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - oxc-resolver
