name: Deploy Inversify docs to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy inversify docusaurus site.
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Compile source files
        run: pnpm run build --filter @inversifyjs/inversify-docs-site

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.ROOT_DOC_PAGES_DEPLOYMENT_PRIVATE_KEY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "inversify.github.io.deploy@github.com"
          git config --global user.name "gh-actions"
          pnpm deploy:inversify:pages
